import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillInstagram
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/food.png";
import design from "../public/health.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/aa.png";
import web2 from "../public/bb.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { SocialIcon } from "react-social-icons";

const SocialLinkButton = ({ url, icon, text }) => {
  return (
    <a href={url} class="inline-flex items-center bg-gray-200 hover:bg-gray-300 text-gray-800 py-2 px-4">
      <SocialIcon icon={icon} class="w-6 h-6 mr-2" />
      <span>{text}</span>
    </a>
  );
};
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Tsega Solomon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Tsega Solomon
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full stack website developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            I am a junior full-stack developer using Python Django
             and PHP laravel as a back-end framework and react.js as a front-end library.
             Join me here.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a
        href="https://www.linkedin.com/in/tsega-solomon-593aa1252/"
        target="_blank"
        rel="noopener noreferrer"
      >
         <a SocialLinkButton url="https://www.linkedin.com/in/tsega-solomon-593aa1252/"><AiFillLinkedin /></a>
      </a>
             
              <a
        href="https://github.com/tsega19/"
        target="_blank"
        rel="noopener noreferrer"
      >
         <a SocialLinkButton url="https://github.com/tsega19"> <AiFillGithub /></a>
      </a>
            
             
  
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Generally, I am offering website development services using different programming languages and frameworks. 
            Specifically using PHP Laravel framework for the backend, python django framework for the backend, and 
            different from libraries such as Bootstrap, react, tailwind, and software design.
            <br />
             So, currently I am willing to work related to my skill with  <span className="text-teal-500">companys </span>
              , for <span className="text-teal-500">startups </span>
             by collaborating with talanted people to create digital products
              for both business and consumer use. also, I am willing to work <span className="text-teal-500">remmote </span> works 
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            This are some of my works
            </p>
         
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
               Nearest helth organizations location tracker
              </h3>
              <p className="py-2">
                This project is basically developed for 
                emergency case health related issue
              
              </p>
              <h4 className="py-4 text-teal-600">Framework and library I used</h4>
              <p className="text-gray-800 py-1">Laravel Framework</p>
              <p className="text-gray-800 py-1">Bootstrap Library</p>
              <p className="text-gray-800 py-1">simple javaScript </p>
              <button class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-full">
              <a
        href="https://github.com/tsega19/"
        target="_blank"
        rel="noopener noreferrer"
      >
         <a SocialLinkButton url="https://github.com/tsega19">Click</a>
      </a>
      </button>
            
      
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Online Food ordering and delivery system 
              </h3>
              <p className="py-2">
              This project is designed for school project. The project 
              is made by group My role was in backed development 
              </p>
              <h4 className="py-4 text-teal-600">Languages</h4>
              <p className="text-gray-800 py-1">PHP</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <button class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-full">
              <a
        href="https://github.com/tsega19/"
        target="_blank"
        rel="noopener noreferrer"
      >
         <a SocialLinkButton url="https://github.com/tsega19">Click </a>
      </a>
      </button>
            
              
            </div>
            
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Certficate</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            These certificates are the ones I gained from Coursera.com 
            by taking full classes and completing all tasks
            </p>
            
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/4 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
         
          </div>
        </section>
        
      </main>
      <footer className="bg-gray-200 dark:bg-gray-900 py-6 px-10 text-gray-800 dark:text-gray-200">
  <div className="flex justify-center gap-4">
    <div className="flex items-center gap-2">
    {/* <svg class="h-8 w-8 text-red-500"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <path d="M15.05 5A5 5 0 0 1 19 8.95M15.05 1A9 9 0 0 1 23 8.94m-1 7.98v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" /></svg> */}
    <svg class="h-8 w-8 text-green-400"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <path d="M15.05 5A5 5 0 0 1 19 8.95M15.05 1A9 9 0 0 1 23 8.94m-1 7.98v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" /></svg>
      <span>Phone: +251932296568</span>
    </div>
    <div className="flex items-center gap-2">
    <svg class="h-8 w-8 text-green-400"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />  <polyline points="22,6 12,13 2,6" /></svg>
      <span>Email: tsega77solomon@gmail.com</span>
    </div>
    <div className="flex items-center gap-2">
    <svg class="h-8 w-8 text-green-400"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 14v3m4-3v3m4-3v3M3 21h18M3 10h18M3 7l9-4 9 4M4 10h16v11H4V10z"/>
</svg>

      <span>Country: Ethiopia, Addis Ababa</span>
    </div>
    <div className="flex items-center gap-2">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        className="w-6 h-6"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M5 13l4 4L19 7"
        />
      </svg>
      <a
        href="https://www.linkedin.com/in/tsega-solomon-593aa1252/"
        target="_blank"
        rel="noopener noreferrer"
      >
         <a SocialLinkButton url="https://www.linkedin.com/in/tsega-solomon-593aa1252/"><AiFillLinkedin /></a>
      </a>
    </div>
  </div>
</footer>
    </div>
  );
}
